openapi: 3.0.3
info:
  title: Hello Spring
  description: A minimal "Hello, world" FOLIO module written in Java, inspired by the `hello-vertx` example.
  license:
    name: Apache License 2.0
    url: https://spdx.org/licenses/Apache-2.0
  version: v1.0
paths:
  /hello:
    get:
      summary: Get "Hello, World!"
      responses:
        "200":
          description: The traditional greeting
          content:
            text/plain:
              schema:
                type: string
                example: "Hello, World!\n"
    post:
      summary: Send data to be wrapped up in a response object.
      requestBody:
        description: Data to be wrapped up in response object
        content:
          application/json:
            schema:
              type: object
              example:
                123:
                  - a
                  - b
                  - c
      responses:
        "200":
          description: The supplied data wrapped up in a JSON object
          content:
            application/json:
              schema:
                type: object
                properties:
                  greeting:
                    type: string
                  data:
                    type: object
                example:
                  greeting: "Hello, World!\n"
                  data:
                    123:
                      - a
                      - b
                      - c
  /sum/body:
    post:
      summary: Get sum of two integers with a JSON blob
      requestBody:
        description: Two integers provided in a JSON blob
        content:
          application/json:
            schema:
              $ref: ./schemas/InputIntegers.yaml
      responses:
        "200":
          description: The sum of two provided integers
          content:
            application/json:
              schema:
                $ref: ./schemas/SumResponse.yaml
  /sum/query:
    get:
      summary: Get sum of two integers with query parameters
      parameters:
        - in: query
          name: a
          schema:
            type: integer
          description: first integer
        - in: query
          name: b
          schema:
            type: integer
          description: second integer
      responses:
        "200":
          description: The sum of two provided integers
          content:
            application/json:
              schema:
                $ref: ./schemas/SumResponse.yaml
  /roll:
    get:
      summary: Roll a dice
      responses:
        "200":
          description: A number from 1-6 represent the result of a dice Roll
          content:
            application/json:
              schema:
                type: integer
                example: 5
    post:
      summary: Roll the dice a given times
      requestBody:
        description: Number of times rolling the dice
        content:
          application/json:
            schema:
              type: integer
              example: 6
      responses:
        "200":
          description: The results of all the rolls
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                example: [1, 2, 3, 4]
        "400":
          description: Bad Request. Number of rolls has to be an integer greater than or equal to 0.
  /book:
    $ref: ./paths/book.yaml
  /book/{id}:
    $ref: ./paths/book-id.yaml
